### ISSUE TITLE
Добавить инструкцию по запуску на MapReduce?

### ISSUE THREAD

**Issue by alexanderpanchenko** [dllllb/sn-profile-matching#1]

**Comment by dllllb** [comment]
Можно в принципе, но провалидировать негде

**Comment by alexanderpanchenko** [comment]
так можно же в докальном режиме или псевдораспеделенном 
главное просто показать как запускать а дальше пусть запускают где угодно

можно как в этом проекте -- https://github.com/johannessimon/noun-sense-induction 
тащим с собой hadoop в зависимостях и запускаем всегда через hadoop
